### ISSUE TITLE
IndexOutOfBoundsException in FormParameter if posted parameter has no value

### ISSUE THREAD

**Issue by raymanoz** [timt/naive-http#6]
Sometime when POST'ing form values, not all fields supply values. When trying to deserialize them, you currently get the above exception.

The following code demonstrates it.

``` scala
import io.shaka.http.FormParameter.deserialize
import org.scalatest.FunSuite

class NaiveHttpTest extends FunSuite {
  test("can deserialize no-value form parameters") {
    assert(deserialize("value=").value == None)
  }
}
```

**Comment by timt** [comment]
Seem you already fixed it ;)

**Comment by raymanoz** [comment]
LOL, yeah. I guess I forgot to also close the bug.
